policy:
  approval:
    - only metadata.json file allowed
approval_rules: 
  - name: only metadata.json file allowed
    requires:
      count: 0
    if:
      only_changed_files:
        paths:
          - src/metadata.json
