name: Changed Files
on: 
  pull_request:
    paths-ignore:
    - 'src/metadata.json'
jobs:
  validate-files-path:
    runs-on: ubuntu-latest
    steps:
      - name: Fail the check
        run: |
          echo "modifying files other than src/metadata.json is not allowed"
          exit (1)
