name: change only src/metadata.json
on: 
  pull_request:
    paths-ignore:
    - 'src/metadata.json'
jobs:
  verify-json-validation:
    runs-on: ubuntu-latest
    steps:
      - name: Limit changed files
        run: |
          echo "modifying files other than src/metadata.json is not allowed"
          exit (1)
